### ISSUE TITLE
Blank Lines

### ISSUE THREAD

**Issue by mattmcnabb** [PoshCode/PSStyleGuide#11]
What is the reasoning behind the statement "End each file with a single blank line?" I haven't seen this as a best practice before. If there is a solid reason, then that reason should be stated.

**Comment by darkoperator** [comment]
Not a best practice but a style deception I have for my modules that I borrowed from my work on ruby following the ruby style guidelines. It is a style guide not a best practice guide.

**Comment by mattmcnabb** [comment]
A style deception? Can you elaborate?

**Comment by darkoperator** [comment]
Style decision (Autocorrect mistake) I made for my modules, after all the guide purpose was not to serve as a general one for the community but one for people that wanted to contribute to my modules. It follows my guidelines but in the last couple of days it was liked by the community in general and got a lot of attention.
