### ISSUE TITLE
Question: Should you/we be working with PowerShell.org?

### ISSUE THREAD

**Issue by Jaykul** [PoshCode/PSStyleGuide#9]
I don't know if you've seen this:
https://www.penflip.com/powershellorg/the-community-book-of-powershell-practices

I'm unhappy with the license, and I **strongly** disagree with their PIPE-01 rule, which is based on people's [visceral reactions to a completely fabricated example](powershell.org/wp/2013/07/16/powershell-great-debate-piping-in-a-script/), and has no general suitability. But other than that, they have a good starting point for this sort of doc ...

**Comment by darkoperator** [comment]
I have not seen it. Not a fan of PowerShell.org <http://powershell.org/> but do admit they do some good. Agree on PIPE-01

**Comment by vors** [comment]
It's really good to see such work. I agree with @Jaykul : it would make sense to collaborate with powershell.org to get a one standard, community-driven place for guidelines. It can also be backed by the set of rules for [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer). I would love to see future development and collaboration around this project.

-Sergei
Windows PowerShell team

**Comment by mattmcnabb** [comment]
It looks like this document is going to grow quite a bit! I wonder if in the long run it will be better to split this up into one document per section? Also, I think overall this document is approaching two different topics - Best Practices and Style Guidelines. Maybe it would be better to split into two docs.

Best practices could be a continuously evolving doc as there can be an endless number of areas to cover (best practices for securing data, writing to DBs, etc.), whereas a style guide can be done once and will remain relatively static. Just a thought...

**Comment by darkoperator** [comment]
Style and best practices do cross from one to the other.

**Comment by Jaykul** [comment]
Thought: PowerShell.org's document has a license which prohibits us from forking it (CC-By-NoDeriv). That means they own it, and nobody else is allowed to modify and distribute -- any modifications are only allowed to happen within their system and with their approval. I understand that, but after thinking about it, I think I'm unlikely to put _significant_ work into it. 

Also, as they say in their [contributing](https://www.penflip.com/powershellorg/contributing-to-powershellorg-ebooks) document, Penflip makes it hard to have conversations about chapters or proposed changes to them. I think that makes Penflip a bad choice for a community-driven best practices book or style guide, where we need to be able to have (and keep record of) discussions in order to end up with something useful.  I don't like the idea that discussions happen in the comments on a blog post or on a separate forum, and then a rule gets written without any link to the discussion.

I've sent mattpenny an email, but I'm not sure that there's anything short of changing their license which could be done to unify this stuff.

**Comment by Jaykul** [comment]
It's definitely worth discussing breaking the document apart #13
And we discussing whether anyone wants to extend to Best Practices #14

**Comment by nightroman** [comment]
It is a useful project and I am looking forward to its development. I have seen
a few similar attempts before but they were not as good as this.

If you are interested, I have a project [PowerShellTraps]. It is not about
guidelines but its goal is also to reveal some DO and DON'T in PowerShell.

[PowerShellTraps]: https://github.com/nightroman/PowerShellTraps

**Comment by Jaykul** [comment]
OK, I officially got Don Jones and PowerShell.org to re-license the book so we can take over development of it ... so the only question is #21
